terms:
  - id: capture
    term: capture
  - id: compression
    term: compression
  - id: creation
    term: creation
  - id: deaccession
    term: deaccession
  - id: decompression
    term: decompression
  - id: decryption
    term: decryption
  - id: deletion
    term: deletion
  - id: digitalSignatureValidation
    term: digital signature validation
  - id: download
    term: download
  - id: fixity check
    term: fixity check
  - id: ingestion
    term: ingestion
  - id: messageDigestCalculation
    term: message digest calculation
  - id: migration
    term: migration
  - id: normalisation
    term: normalisation
  - id: replication
    term: replication
  - id: update
    term: update
  - id: validation
    term: validation
  - id: virus check
    term: virus check
