terms:
  - id: contactPerson
    term: ContactPerson
  - id: dataCollector
    term: DataCollector
  - id: dataCurator
    term: DataCurator
  - id: dataManager
    term: DataManager
  - id: distributor
    term: Distributor
  - id: editor
    term: Editor
  - id: hostingInstitution
    term: HostingInstitution
  - id: producer
    term: Producer
  - id: projectLeader
    term: ProjectLeader
  - id: projectManager
    term: ProjectManager
  - id: projectMember
    term: ProjectMember
  - id: registrationAgency
    term: RegistrationAgency
  - id: registrationAuthority
    term: RegistrationAuthority
  - id: relatedPerson
    term: RelatedPerson
  - id: researcher
    term: Researcher
  - id: researchGroup
    term: ResearchGroup
  - id: rightsHolder
    term: RightsHolder
  - id: sponsor
    term: Sponsor
  - id: supervisor
    term: Supervisor
  - id: workPackageLeader
    term: WorkPackageLeader
  - id: other
    term: Other

  - id: administrator
    term: Administrator
  - id: contactPerson
    term: ContactPerson
  - id: dataAnalyser
    term: DataAnalyser
  - id: dataCreator
    term: DataCreator
  - id: investigator
    term: Investigator
  - id: publisher
    term: Publisher
  - id: author
    term: Author
  - id: depositingUser
    term: DepositingUser
