version: '2.1'

services:
  db:
    build: db/
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  solr:
    build:
      context: .
      dockerfile: solr/Dockerfile
    volumes:
      - solr_home:/solr_home
    ports:
      - "8983:8983"
  
  redis:
    image: redis:3.2
  
  modeshape:
    image: jboss/modeshape
  
  bundle: # cache for gems to speed up bundle install time
    image: willow_willow
    command: echo "configured bundle cache"
    volumes:
      - /bundle

  geoblacklight_bundle: # cache for gems to speed up bundle install time
    image: willow_geoblacklight
    command: echo "configured bundle cache"
    volumes:
      - /geoblacklight_bundle
  
  fedora:
    build: fedora_commons/
    links:
      - db
    ports:
      - "8080:8080"
    #environment:
      #      JAVA_OPTS: >
      #        -Dfile.encoding=UTF-8
      #        -Dfcrepo.home=/mnt/data/fcrepo
      #        -Dfcrepo.ispn.alternative.cache=ispn.alt.cache
      #        -Dfcrepo.ispn.binary.cache=ispn.binary.cache
      #        -Dfcrepo.ispn.cache=ispn.cache
      #        -Dfcrepo.ispn.binary.alternative.cache=ispn.binary.alt.cache
      #        -Dfcrepo.ispn.repo.cache=ispn.repo.cache
      #        -Dfcrepo.ispn.postgresql.username=${POSTGRES_USER}
      #        -Dfcrepo.ispn.postgresql.password=${POSTGRES_PASSWORD}
      #        -Dfcrepo.ispn.postgresql.host=db
      #        -Dfcrepo.ispn.postgresql.port=5432
      #        -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json
      #        -Dfcrepo.modeshape.index.directory=modeshape.index
      #        -Dfcrepo.binary.directory=binary.store
      #        -Dfcrepo.activemq.directory=activemq
      #        -Dcom.arjuna.ats.arjuna.common.ObjectStoreEnvironmentBean.default.objectStoreDir=arjuna.common.object.store
      #        -Dcom.arjuna.ats.arjuna.objectstore.objectStoreDir=arjuna.object.store
      #        -Dnet.sf.ehcache.skipUpdateCheck=true
      #        -Dfcrepo.audit.container=/audit
      #        -Djava.security.egd=file:/dev/./urandom
      #        -XX:+UseConcMarkSweepGC
      #        -XX:+CMSClassUnloadingEnabled
      #        -XX:ConcGCThreads=5
      #        -XX:MaxGCPauseMillis=200
      #        -XX:ParallelGCThreads=20
      #        -XX:MaxMetaspaceSize=512M
      #        -Xms1024m
      #        -Xmx2048m
      #   -Dfcrepo.activemq.configuration=file:/etc/fcrepo/activemq.xml
      #   -Dfcrepo.ispn.configuration=/etc/fcrepo/infinispan.xml
      #   -Dfcrepo.auth.webac.authorization=/etc/fcrepo/root-authentication.ttl
      #   -Dfcrepo.spring.audit.configuration=file:/etc/fcrepo/audit.xml
      #   -Dlogback.configurationFile=/etc/fcrepo/logback.xml
    volumes:
       - fcrepo4_home:/fcrepo4_home/
       - fcrepo4_data:/mnt/data/fcrepo/
       - fcrepo4_etc:/etc/fcrepo/
       #- /Users/martyn/temp/fcrepo4_home_temp:/fcrepo4_home_temp/
    depends_on:
      db:
        condition: service_started
  
  willow:
    build: willow/
    env_file: .env
    command: ./startup.sh
    ports:
      - "3000:3000"
    links:
      - redis
      - solr
      - db
      - fedora
    depends_on:
      fedora:
        condition: service_healthy
    volumes_from:
      - bundle
    volumes:
      - ./willow:/willow_source

  geoblacklight:
    build: geoblacklight/
    env_file: .env
    command: ./startup.sh
    ports:
      - "3010:3010"
    volumes_from:
      - geoblacklight_bundle
    volumes:
      - ./geoblacklight:/geoblacklight_source
    links:
      - solr
      - db


volumes:
  webapps: {}
  fcrepo4_home: {}
  fcrepo4_data: {}
  fcrepo4_etc: {}
  postgres_data: {}
  solr_home: {}
