version: '2.1'

services:
  db:
    build: db/
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  solr:
    build:
      context: .
      dockerfile: solr/Dockerfile
    volumes:
      - solr_home:/solr_home
    ports:
      - "8983:8983"
  
  redis:
    build: redis/
    volumes:
      - redis_data:/data

  # cache for gems to speed up bundle install time
  #used by willow and geoblacklight
  bundle_cache:
    image: busybox # tiny linux
    volumes:
      - bundle_cache:/bundle
  
  fedora:
    env_file: .env
    build: fedora_commons/
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
       - fcrepo4_home:/fcrepo4_home/
       - fcrepo4_data:/fcrepo4_data/
    depends_on:
      db:
        condition: service_healthy
  
  willow:
    build: willow/
    env_file: .env
    ports:
      - "${WILLOW_EXPOSED_PORT:-3000}:3000"
    links:
      - redis
      - solr
      - db
      - fedora
    depends_on:
      fedora:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes_from:
      - bundle_cache
    volumes:
      - ./willow:/willow

  geoblacklight:
    build: geoblacklight/
    env_file: .env
    command: ./startup.sh
    ports:
      - "${GEOBLACKLIGHT_EXPOSED_PORT:-3010}:3010"
    volumes_from:
      - bundle_cache
    volumes:
      - ./geoblacklight:/geoblacklight_source
    links:
      - solr
      - db

volumes:
  redis_data: {}
  fcrepo4_home: {}
  fcrepo4_data: {}
  postgres_data: {}
  solr_home: {}
  bundle_cache: {}
