version: '2.1'

services:
  db:
    build: db/
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  solr:
    build:
      context: .
      dockerfile: solr/Dockerfile
    volumes:
      - solr_home:/solr_home
    ports:
      - "8983:8983"
  
  redis:
    image: redis:3.2
  
  willow_bundle: # cache for gems to speed up bundle install time
    image: willow_willow
    command: echo "configured bundle cache"
    volumes:
      - /willow_bundle

  geoblacklight_bundle: # cache for gems to speed up bundle install time
    image: willow_geoblacklight
    command: echo "configured bundle cache"
    volumes:
      - /geoblacklight_bundle
  
  fedora:
    env_file: .env
    build: fedora_commons/
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
       - fcrepo4_home:/fcrepo4_home/
       - fcrepo4_data:/fcrepo4_data/
    depends_on:
      db:
        condition: service_healthy
  
  willow:
    build: willow/
    env_file: .env
    command: ./startup.sh
    ports:
      - "3000:3000"
    links:
      - redis
      - solr
      - db
      - fedora
    depends_on:
      fedora:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes_from:
      - willow_bundle
    volumes:
      - ./willow:/willow_source

  geoblacklight:
    build: geoblacklight/
    env_file: .env
    command: ./startup.sh
    ports:
      - "3010:3010"
    volumes_from:
      - geoblacklight_bundle
    volumes:
      - ./geoblacklight:/geoblacklight_source
    links:
      - solr
      - db

volumes:
  fcrepo4_home: {}
  fcrepo4_data: {}
  postgres_data: {}
  solr_home: {}
